# Generated by Django 5.2.8 on 2025-11-26 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_nom', models.CharField(max_length=255)),
                ('description_role', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_nom', models.CharField(max_length=255)),
                ('id_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.BigIntegerField()),
                ('nom_utilisateur', models.CharField(max_length=255)),
                ('prenom_utilisateur', models.CharField(max_length=255)),
                ('mot_de_pass', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('mail', models.EmailField(max_length=254)),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.role')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service')),
            ],
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_adresse', models.CharField(max_length=255)),
                ('navigateur', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codesh', models.CharField(max_length=255)),
                ('descrip', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pu_fact', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pu_redr', models.DecimalField(decimal_places=2, max_digits=19)),
                ('methode', models.CharField(max_length=255)),
                ('incoterm', models.CharField(max_length=255)),
                ('devise', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('ref_fact', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('details_marchandises', models.CharField(max_length=255)),
                ('poid_brut', models.DecimalField(decimal_places=2, max_digits=19)),
                ('poid_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('exportateur', models.CharField(max_length=255)),
                ('pays_destinataire', models.CharField(max_length=255)),
                ('importateur', models.CharField(max_length=255)),
                ('conditionnement', models.CharField(max_length=255)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('date_effet', models.DateField()),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueValeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ_modifies', models.CharField(max_length=255)),
                ('ancienne_valeur', models.CharField(max_length=255)),
                ('nouvelle_valeur', models.CharField(max_length=255)),
                ('date_modif', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.utilisateur')),
                ('id_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valeur')),
            ],
        ),
        migrations.CreateModel(
            name='ValeurExtrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_extraction', models.DateField()),
                ('serdau', models.CharField(max_length=255)),
                ('datedau', models.DateField()),
                ('liquide', models.CharField(max_length=255)),
                ('dateliquide', models.DateField()),
                ('importateur', models.CharField(max_length=255)),
                ('exportateur', models.CharField(max_length=255)),
                ('pays_destinataire', models.CharField(max_length=255)),
                ('description_article', models.CharField(max_length=255)),
                ('poid_brut', models.DecimalField(decimal_places=2, max_digits=19)),
                ('poid_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=19)),
                ('unite', models.CharField(max_length=255)),
                ('prix_article', models.DecimalField(decimal_places=2, max_digits=19)),
                ('incoterm', models.CharField(max_length=255)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='valeur',
            name='id_extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.valeurextrait'),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('id_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valeurextrait')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.utilisateur')),
            ],
        ),
    ]
